numpy与scipy的傅里叶使用

In [7]:
import scipy as sy
import numpy as np
from numpy.fft import fft,ifft
from PIL import Image

In [14]:
cat = Image.open('C:\\Users\\向\\Desktop\\cat.png')
print(cat)

<PIL.PngImagePlugin.PngImageFile image mode=RGBA size=196x256 at 0x1DBBF2024A8>


In [15]:
#转换成int型数据

In [30]:
cat_data = np.frombuffer(cat.tobytes(),dtype=np.int8)
cat_data#大于128会将其变成复数

array([ -1,  -1,  -1, ..., 117, 117,  -1], dtype=int8)

In [31]:
cat_data_fft=fft(cat_data)#傅里叶转换
print(cat_data_fft)#将真实数据转换为频域

[1557991.             +0.j          283117.82892171+696084.42571259j
 -106408.01817798+581894.60804732j ... -280578.57610653-111503.29438358j
 -106408.01817798-581894.60804732j  283117.82892171-696084.42571259j]


In [32]:
#去掉低频的数据，变成0

In [33]:
cat_data_fft=np.where(np.abs(cat_data_fft)<1e5,0,cat_data_fft)#小于1e5的数据置0

In [34]:
cat_data_fft[np.where(np.abs(cat_data_fft)<1e5)]=0#与上述的一样

In [35]:
#傅里叶反转
cat_data_ifft=ifft(cat_data_fft)
cat_data_ifft

array([-18.08657279-5.19425772e-16j, -17.29341292+2.74893487e-15j,
       -17.53985353-5.34096576e-15j, ..., -10.11897027-4.93883881e-15j,
       -11.74740475-1.40743481e-15j, -11.72989046+1.25689043e-15j])

In [52]:
cat_data_real=np.real(cat_data_ifft)#只获取实数部分
cat_data_result = np.int8(cat_data_real)#去掉小数部分
print(cat_data_result)

[-18 -17 -17 ... -10 -11 -11]


In [53]:
cat_image = Image.frombytes(size = cat.size,mode = cat.mode,data = cat_data_result)

In [54]:
cat_image.show()